name: Build Projects

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build DATCodecTool
      run: msbuild DATCodecTool.csproj /p:Configuration=Release

    - name: Build DATMovieTool
      run: msbuild DATMovieTool.csproj /p:Configuration=Release

    - name: Build DATSpeechTool
      run: msbuild DATSpeechTool.csproj /p:Configuration=Release

    - name: Upload DATCodecTool artifacts
      uses: actions/upload-artifact@v2
      with:
        name: DATCodecTool-Build
        path: '**/DATCodecTool/bin/Release/**/*.exe'

    - name: Upload DATMovieTool artifacts
      uses: actions/upload-artifact@v2
      with:
        name: DATMovieTool-Build
        path: '**/DATMovieTool/bin/Release/**/*.exe'

    - name: Upload DATSpeechTool artifacts
      uses: actions/upload-artifact@v2
      with:
        name: DATSpeechTool-Build
        path: '**/DATSpeechTool/bin/Release/**/*.exe'
