name: Build Projects

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build DATCodecTool
      run: msbuild DATCodecTool/DATCodecTool.csproj /p:Configuration=Release

    - name: Build DATMovieTool
      run: msbuild DATMovieTool/DATMovieTool.csproj /p:Configuration=Release

    - name: Build DATSpeechTool
      run: msbuild DATSpeechTool/DATSpeechTool.csproj /p:Configuration=Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Built-Artifacts
        path: |
          DATCodecTool/bin/Release/
          DATMovieTool/bin/Release/
          DATSpeechTool/bin/Release/
